### ISSUE TITLE
About 4.5. Applying VL-PET Designs to Existing Methods

### ISSUE THREAD

**Issue by 123456789asdfjkl** [HenryHZY/VL-PET#4]
您好！感谢您的杰出工作！我想问一下您这个4.5节的实验细节，是保持现有方法在解码器的设计不变，在编码器添加VL-PET吗？

**Comment by HenryHZY** [comment]
Hi, @123456789asdfjkl 
As mentioned in section 4.5, we would like to transfer some of our VL-PET designs to state-of-the-art PET techniques.
1. For encoders, we introduce Granularity-controlled Mechanism to the encoder PET modules (e.g., G_large). By the way, the encoder LNs are trainable.
2. For decoder, to simplify the validation of lightweight PET module designs, we only retain the decoder PET modules in the cross-attention modules from their conventional designs. That is, we remove their decoder PET modules in the self-attention modules and feed-forward modules.

**Comment by 123456789asdfjkl** [comment]
好的，感谢您的解答

**Comment by HenryHZY** [comment]
Thanks for you issue. I think we can close this issue now:)
