### ISSUE TITLE
For T5-base model, when I used LoRA to reproduce previous experimence (Ablation study), I obtained particularly poor performance.(acc: VQA-23.26, GQA-17.96, NLVR-50.04; CIDEr:coco-7.34) Why?

### ISSUE THREAD

**Issue by ywxsuperstar** [HenryHZY/VL-PET#5]
Hi,

When using the T5-base model with LoRA to reproduce a previous experiment (Ablation study), I achieved particularly poor performance (VQA: 23.26, GQA: 17.96, NLVR: 50.04, CIDEr: COCO: 7.34). Could you help me understand why?

**Comment by HenryHZY** [comment]
Do you refer to VL-LoRA? Please check its implementation & scripts from VL-Adapter repo (https://github.com/ylsung/VL_adapter).
